[cmake]
version = "3.30"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "EncodeHex"
include-before = ["cmake/msvc-configurations.cmake"]
include-after = ["cmake/msvc-flags.cmake"]
msvc-runtime = "static"

[fetch-content.x64dbg]
url = "https://github.com/x64dbg/x64dbg/releases/download/2025.08.19/x64dbg-pluginsdk-cmake.zip"
tag = "2025.08.19"
sha256 = "56877037bc05b15099299e0a03a8bcb0afc6380785cd2dc92d04c53b738549d3"

[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target.EncodeHex]
type = "plugin"
sources = [
    "src/*.cpp",
    "src/*.h",
]
compile-features = ["cxx_std_17"]