name: Build
on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-latest
    permissions:
      contents: write # Allow job to create a release
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Build (x64)
        run: |
          mkdir package\x64\plugins
          cmake -B build64 -A x64
          cmake --build build64 --config Release
          copy build64\Release\*.dp64 package\x64\plugins\

      - name: Build (x32)
        run: |
          mkdir package\x32\plugins
          cmake -B build32 -A Win32
          cmake --build build32 --config Release
          copy build32\Release\*.dp32 package\x32\plugins\

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: package/

      - name: Compress artifacts
        uses: vimtor/action-zip@1379ea20d4c5705669ba81fd626dd01b1c738f26 # v1.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: package/
          dest: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
